---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: redis
  name: redis
  namespace: FQ_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:REDIS_TAG
        name: redis
        resources: {}
        tty: true
        stdin: true
      restartPolicy: Always
status: {}
